### ISSUE TITLE
Page 1, Step 6

### ISSUE THREAD

**Issue by lmalhoit** [CiscoDevNet/coding-series-learning-labs#1]
"Select the latest API version." 

I think this is out of order and the page has been updated, so the screenshot also needs to be updated. It should be 

Step 6. Click on API Reference (with an updated screenshot)
Step 7. Select the latest API version
Step 8. Keep the APIC-EM API Reference documentation open in a separate tab. This will be a useful reference while you work on this lab.

**Comment by annegentle** [comment]
Fixed with PR #2 - closing Issue.
